spring:
  application:
    name: foreing-exchange
    h2:
      console:
        enabled: true
        path: /h2
    datasource:
      url: jdbc:h2:file:~/test
      username: sa
      password:
      driverClassName: org.h2.Driver

rates-api:
  base-url: 'https://api.ratesapi.io'
  valid-currency-list: GBP,HKD,IDR,ILS,DKK,INR,CHF,MXN,CZK,SGD,THB,HRK,EUR,MYR,NOK,CNY,BGN,PHP,PLN,ZAR,CAD,ISK,BRL,RON,NZD,TRY,JPY,RUB,KRW,USD,AUD,HUF,SEK
ogging:
  level:
    ROOT: INFO
    feign:
      Logger: DEBUG
  file:
    max-history: 0
    max-size: 1GB
default:
  locale: en_US

feign:
  connect:
    timeout: 1500
  read:
    timeout: 1500